WORKDIR /etc/apt
RUN git clone https://github.com/h4ppyy/docker_sources.list
RUN mv docker_sources.list/sources.list sources.list
RUN apt-get update
RUN apt-get install -y vim
RUN apt-get install -y curl
