version: "2.1"

services:
  django:
    command: bash -c 'source /root/venv/bin/activate && while true; do python /root/main/manage.py runserver 0.0.0.0:8000; sleep 2; done'
    #command: bash
    container_name: main.django
    depends_on:
      - mysql
    stdin_open: true
    tty: true
    image: h4ppyy/main.django:v3
    ports:
      - "7000:8000"
    volumes:
      - ./:/root/main
  mysql:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: main.mysql
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "0000"
    image: mysql:5.6
    ports:
      - "7001:3306"