FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD . /code/
RUN pip install -r requirements.txt

WORKDIR /etc/apt
RUN cp /code/sources.list .
RUN apt-get update
RUN apt-get install -y vim

WORKDIR /code
